### ISSUE TITLE
Regarding Mask Image

### ISSUE THREAD

**Issue by jaykpatel1996** [TUI-NICR/deep-orientation#10]
Hi author, 

Wonderful code. Is there any way to generate the mask of the image which your code uses?

**Comment by danielS91** [comment]
Which mask do you mean exactly?

**Comment by jaykpatel1996** [comment]
Hi @danielS91, 

There are mask images associated with each RGB image. if we go to 
**deep-orientation\nicr_rgb_d_orientation_data_set_examples\small_patches**
there are three images associated with one data Image 
1) RGB Image (p0-jacke-Kinect4-169-Take1_RGB.png)
2) Mask Image (p0-jacke-Kinect4-169-Take1_Mask.png)
3) Depth Image(p0-jacke-Kinect4-169-Take1_Depth.pgm)


I was wondering how the Mask image is obtained. I was trying to test the existing mobileNet Model on my dataset (using inference.py), which only consists of the RBG images. 

Is there any way to create the mask of corresponding RGB image?

**Comment by danielS91** [comment]
The data was recorded in a static sensor setup. We used a background model retrieved from depth images to create masks for each RGB image (we refer to the paper for more details).

However, application requires some kind of person segmentation. In our work, we use [1] and a person classifier to segment the person based on the depth image.

---
[1] O. H. Jafari, et al., “Real-time RGB-D based people detection and tracking for mobile robots and head-worn cameras,” in Proc. of ICRA, 2014, pp. 5636–5643.

**Comment by jaykpatel1996** [comment]
Hi @danielS91 Thank you!
